In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [3]:
dataset = pd.read_csv('50_Startups.csv')

dataset = pd.get_dummies(dataset, drop_first=True)

dataset.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,False,True
1,162597.70,151377.59,443898.53,191792.06,False,False
2,153441.51,101145.55,407934.54,191050.39,True,False
3,144372.41,118671.85,383199.62,182901.99,False,True
4,142107.34,91391.77,366168.42,166187.94,True,False

In [4]:
indep = dataset[['R&D Spend',
                 'Administration',
                 'Marketing Spend',
                 'State_Florida',
                 'State_New York']]

dep = dataset[['Profit']]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    indep,
    dep,
    test_size=1/3,
    random_state=0
)

In [6]:
regressor = DecisionTreeRegressor(random_state=0)

regressor.fit(X_train, y_train.values.ravel())

y_pred = regressor.predict(X_test)

r_score = r2_score(y_test, y_pred)

print("R2 Score:", r_score)

R2 Score: 0.8539797745006693

In [7]:
criteria = ['squared_error', 'absolute_error', 'poisson']
max_features_values = [None, 'sqrt', 'log2']
splitter_values = ['best', 'random']

results = []

for criterion in criteria:
    for max_features in max_features_values:
        for splitter in splitter_values:

            regressor = DecisionTreeRegressor(
                criterion=criterion,
                max_features=max_features,
                splitter=splitter,
                random_state=0
            )

            regressor.fit(X_train, y_train.values.ravel())

            y_pred = regressor.predict(X_test)

            r_score = r2_score(y_test, y_pred)

            results.append({
                'Criterion': criterion,
                'Max Features': max_features,
                'Splitter': splitter,
                'R2': r_score
            })

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by='R2',
    ascending=False
)

results_df

         Criterion Max Features Splitter        R2
6   absolute_error          NaN     best  0.907009
12         poisson          NaN     best  0.901277
0    squared_error          NaN     best  0.853980
14         poisson         sqrt     best  0.801405
16         poisson         log2     best  0.801405
4    squared_error         log2     best  0.728250
2    squared_error         sqrt     best  0.728250
7   absolute_error          NaN   random  0.716623
1    squared_error          NaN   random  0.625621
13         poisson          NaN   random  0.625621
10  absolute_error         log2     best -0.057500
8   absolute_error         sqrt     best -0.057500
9   absolute_error         sqrt   random -0.436649
11  absolute_error         log2   random -0.436649
3    squared_error         sqrt   random -0.951044
5    squared_error         log2   random -0.951044
15         poisson         sqrt   random -0.951044
17         poisson         log2   random -0.951044

In [8]:
## Additional Hyper Tuning

max_depth_values = [None, 2, 3, 5, 8, 10, 15]

max_depth_results = []

for max_depth_value in max_depth_values:

    regressor = DecisionTreeRegressor(
        criterion='absolute_error',
        max_features=None,
        splitter='best',
        max_depth=max_depth_value,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    max_depth_results.append({
        'max_depth': max_depth_value,
        'R2': r_score
    })

max_depth_df = pd.DataFrame(max_depth_results)

max_depth_df = max_depth_df.sort_values(
    by='R2',
    ascending=False
)

max_depth_df

   max_depth        R2
3        5.0  0.918704
4        8.0  0.907009
0        NaN  0.907009
5       10.0  0.907009
6       15.0  0.907009
2        3.0  0.856996
1        2.0  0.693012

In [9]:
min_samples_split_values = [2, 5, 10, 20]

min_samples_split_results = []

for min_samples_split_value in min_samples_split_values:

    regressor = DecisionTreeRegressor(
        criterion='absolute_error',
        max_features=None,
        splitter='best',
        max_depth=5,
        min_samples_split=min_samples_split_value,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    min_samples_split_results.append({
        'min_samples_split': min_samples_split_value,
        'R2': r_score
    })

min_samples_split_df = pd.DataFrame(min_samples_split_results)

min_samples_split_df = min_samples_split_df.sort_values(
    by='R2',
    ascending=False
)

min_samples_split_df

   min_samples_split        R2
0                  2  0.918704
1                  5  0.889418
2                 10  0.778003
3                 20  0.290581

In [10]:
min_samples_leaf_values = [1, 2, 5, 10]

min_samples_leaf_results = []

for min_samples_leaf_value in min_samples_leaf_values:

    regressor = DecisionTreeRegressor(
        criterion='absolute_error',
        max_features=None,
        splitter='best',
        max_depth=5,
        min_samples_split=2,
        min_samples_leaf=min_samples_leaf_value,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    min_samples_leaf_results.append({
        'min_samples_leaf': min_samples_leaf_value,
        'R2': r_score
    })

min_samples_leaf_df = pd.DataFrame(min_samples_leaf_results)

min_samples_leaf_df = min_samples_leaf_df.sort_values(
    by='R2',
    ascending=False
)

min_samples_leaf_df

   min_samples_leaf        R2
1                 2  0.921320
0                 1  0.918704
2                 5  0.778003
3                10  0.290581

In [11]:
max_leaf_nodes_values = [None, 5, 10, 20, 50]

max_leaf_nodes_results = []

for max_leaf_nodes_value in max_leaf_nodes_values:

    regressor = DecisionTreeRegressor(
        criterion='absolute_error',
        max_features=None,
        splitter='best',
        max_depth=5,
        min_samples_split=2,
        min_samples_leaf=2,
        max_leaf_nodes=max_leaf_nodes_value,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    max_leaf_nodes_results.append({
        'max_leaf_nodes': max_leaf_nodes_value,
        'R2': r_score
    })

max_leaf_nodes_df = pd.DataFrame(max_leaf_nodes_results)

max_leaf_nodes_df = max_leaf_nodes_df.sort_values(
    by='R2',
    ascending=False
)

max_leaf_nodes_df

   max_leaf_nodes        R2
0             NaN  0.921320
4            50.0  0.921320
3            20.0  0.921320
2            10.0  0.893102
1             5.0  0.737482

In [12]:
min_impurity_decrease_values = [0, 0.001, 0.01, 0.05]

min_impurity_results = []

for min_impurity_value in min_impurity_decrease_values:

    regressor = DecisionTreeRegressor(
        criterion='absolute_error',
        max_features=None,
        splitter='best',
        max_depth=5,
        min_samples_split=2,
        min_samples_leaf=2,
        max_leaf_nodes=None,
        min_impurity_decrease=min_impurity_value,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    min_impurity_results.append({
        'min_impurity_decrease': min_impurity_value,
        'R2': r_score
    })

min_impurity_df = pd.DataFrame(min_impurity_results)

min_impurity_df = min_impurity_df.sort_values(
    by='R2',
    ascending=False
)

min_impurity_df

   min_impurity_decrease       R2
0                  0.000  0.92132
1                  0.001  0.92132
2                  0.010  0.92132
3                  0.050  0.92132

In [13]:
ccp_alpha_values = [0, 0.001, 0.01, 0.05]

ccp_alpha_results = []

for ccp_alpha_value in ccp_alpha_values:

    regressor = DecisionTreeRegressor(
        criterion='absolute_error',
        max_features=None,
        splitter='best',
        max_depth=5,
        min_samples_split=2,
        min_samples_leaf=2,
        max_leaf_nodes=None,
        min_impurity_decrease=0,
        ccp_alpha=ccp_alpha_value,
        random_state=0
    )

    regressor.fit(X_train, y_train.values.ravel())

    y_pred = regressor.predict(X_test)

    r_score = r2_score(y_test, y_pred)

    ccp_alpha_results.append({
        'ccp_alpha': ccp_alpha_value,
        'R2': r_score
    })

ccp_alpha_df = pd.DataFrame(ccp_alpha_results)

ccp_alpha_df = ccp_alpha_df.sort_values(
    by='R2',
    ascending=False
)

ccp_alpha_df

   ccp_alpha       R2
0      0.000  0.92132
1      0.001  0.92132
2      0.010  0.92132
3      0.050  0.92132