In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")

dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
dataset.shape

(1338, 6)

In [4]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 72.2 KB

In [5]:
dataset = pd.get_dummies(dataset, drop_first=True, dtype=int)

dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [6]:
independent = dataset[
    ['age',
     'bmi',
     'children',
     'sex_male',
     'smoker_yes']
]

In [7]:
dependent = dataset[['charges']]

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    independent,
    dependent,
    test_size=0.30,
    random_state=0
)

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
regressor = LinearRegression()

regressor.fit(X_train, y_train.values.ravel())

y_pred = regressor.predict(X_test)

In [11]:
from sklearn.metrics import r2_score

r_score = r2_score(y_test, y_pred)

print("R2 Score:", r_score)

R2 Score: 0.7894790349867009

In [12]:
fit_intercept_values = [True, False]
positive_values = [False, True]

results = []

for fit_intercept in fit_intercept_values:
    for positive in positive_values:

        regressor = LinearRegression(
            fit_intercept=fit_intercept,
            positive=positive
        )

        regressor.fit(X_train, y_train.values.ravel())

        y_pred = regressor.predict(X_test)

        r_score = r2_score(y_test, y_pred)

        results.append({
            'fit_intercept': fit_intercept,
            'positive': positive,
            'R2': r_score
        })

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by='R2',
    ascending=False
)

results_df

   fit_intercept  positive        R2
0           True     False  0.789479
1           True      True  0.789443
2          False     False  0.762372
3          False      True  0.761433